/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DataMsg'
 * message type.
 */

public class DataMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 5;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 1;

    /** Create a new DataMsg of size 5. */
    public DataMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DataMsg of the given data_length. */
    public DataMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg with the given data_length
     * and base offset.
     */
    public DataMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg using the given byte array
     * as backing store.
     */
    public DataMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public DataMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DataMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg embedded in the given message
     * at the given base offset.
     */
    public DataMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg embedded in the given message
     * at the given base offset and length.
     */
    public DataMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DataMsg> \n";
      try {
        s += "  [NodeID=0x"+Long.toHexString(get_NodeID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [Temp_data=0x"+Long.toHexString(get_Temp_data())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [Hum_data=0x"+Long.toHexString(get_Hum_data())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: NodeID
    //   Field type: byte, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'NodeID' is signed (false).
     */
    public static boolean isSigned_NodeID() {
        return false;
    }

    /**
     * Return whether the field 'NodeID' is an array (false).
     */
    public static boolean isArray_NodeID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'NodeID'
     */
    public static int offset_NodeID() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'NodeID'
     */
    public static int offsetBits_NodeID() {
        return 0;
    }

    /**
     * Return the value (as a byte) of the field 'NodeID'
     */
    public byte get_NodeID() {
        return (byte)getSIntBEElement(offsetBits_NodeID(), 8);
    }

    /**
     * Set the value of the field 'NodeID'
     */
    public void set_NodeID(byte value) {
        setSIntBEElement(offsetBits_NodeID(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'NodeID'
     */
    public static int size_NodeID() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'NodeID'
     */
    public static int sizeBits_NodeID() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: Temp_data
    //   Field type: short, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'Temp_data' is signed (false).
     */
    public static boolean isSigned_Temp_data() {
        return false;
    }

    /**
     * Return whether the field 'Temp_data' is an array (false).
     */
    public static boolean isArray_Temp_data() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'Temp_data'
     */
    public static int offset_Temp_data() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'Temp_data'
     */
    public static int offsetBits_Temp_data() {
        return 8;
    }

    /**
     * Return the value (as a short) of the field 'Temp_data'
     */
    public short get_Temp_data() {
        return (short)getSIntBEElement(offsetBits_Temp_data(), 16);
    }

    /**
     * Set the value of the field 'Temp_data'
     */
    public void set_Temp_data(short value) {
        setSIntBEElement(offsetBits_Temp_data(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'Temp_data'
     */
    public static int size_Temp_data() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'Temp_data'
     */
    public static int sizeBits_Temp_data() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: Hum_data
    //   Field type: int, unsigned
    //   Offset (bits): 24
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'Hum_data' is signed (false).
     */
    public static boolean isSigned_Hum_data() {
        return false;
    }

    /**
     * Return whether the field 'Hum_data' is an array (false).
     */
    public static boolean isArray_Hum_data() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'Hum_data'
     */
    public static int offset_Hum_data() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'Hum_data'
     */
    public static int offsetBits_Hum_data() {
        return 24;
    }

    /**
     * Return the value (as a int) of the field 'Hum_data'
     */
    public int get_Hum_data() {
        return (int)getUIntBEElement(offsetBits_Hum_data(), 16);
    }

    /**
     * Set the value of the field 'Hum_data'
     */
    public void set_Hum_data(int value) {
        setUIntBEElement(offsetBits_Hum_data(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'Hum_data'
     */
    public static int size_Hum_data() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'Hum_data'
     */
    public static int sizeBits_Hum_data() {
        return 16;
    }

}
